language: go
go:
  - 1.13.x
  - 1.14.x
os:
  - linux
  - osx
  - windows
go_import_path: github.com/vechain/thor
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y make; choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH"; fi
install:
  - make dep
script:
  - make all test
